### PR TITLE
Add Colors Section

### PR DESCRIPTION
**Pull request by RenegadeAI**
I think I did it correct this time

### CODE REVIEW

**Comment by Thatplayer** [comment]
What was wrong with the other one?

**Comment by RenegadeAI** [comment]
I think I had my repositories set up wrong and it was pulling out of master instead of gh-pages.

I don't know if it would have affected anything but I just reset mine and re-did it since I have no idea what i'm doing.

**Comment by Thatplayer** [comment]
Yeah 2nd pull request was just alot cleaner since it was only 1 commit.

**Comment by RenegadeAI** [comment]
Yeah, the other one was mostly commits that cancelled each other out since I was trying to get it to commit to my gh-pages.

**Pull request merged**
